version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:20.11.1-alpine
    container_name: app
    command: npm run start:dev
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - docker-network
  
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5432:5432"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
