version: '3.9'

services:
  node-app:
    build: 
      context: .
    container_name: node-app
    restart: always
    image: node-app-img
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
      ENV_MODE: ${ENV_MODE}
      PORT: ${PORT}
      POSTGRES_SYNC: true
    networks:
      - docker-network

  postgres:
    build:
      context: ./db
    container_name: db
    restart: always
    image: postgres
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: postgres
    volumes:
      - postdata:/var/lib/postgresql/data
      - postlogs:/var/log/postgresql
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  postdata:
  node_modules:
  postlogs:
